version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: safe
      POSTGRES_DB: migrations
